try{
  someFucntion();

} catch (error) {

  try {
    someOtherFunction
  }catch (error) {
    console.log("The error " + error.name + "has the following to say: " + error.message);
  }
}


console.log("your program has sucessfully completed");








// oct29
//Week 2 day 7